import { z } from "zod";
import {
  isValidSkillName,
  SKILL_LIMITS,
  type SkillDocument,
  type SkillSummary,
} from "@/lib/skills";

export type SkillsToolRuntime = {
  loadSkillContent: (name: string) => Promise<string | null>;
  createSkill?: (skill: SkillDocument) => Promise<SkillSummary>;
};

export const skillTools = {
  load_skill: {
    description:
      "Load task-specific operating instructions before acting when an exact entry under Available skills clearly matches the request. Do not guess names or load skills speculatively.",
    inputSchema: z.object({
      name: z
        .string()
        .min(1)
        .describe("Exact skill name from the Available skills list"),
    }),
  },
  create_skill: {
    description:
      "Create and install a new personal Nimruz skill when the user explicitly asks for one. Provide the skill name, trigger-focused description, and complete Markdown instructions; the app adds valid SKILL.md frontmatter and makes the skill available in Settings.",
    inputSchema: z.object({
      name: z
        .string()
        .max(SKILL_LIMITS.name)
        .refine(isValidSkillName, {
          message:
            "Use lowercase letters, digits, and single hyphens only (for example: review-pull-request).",
        })
        .describe(
          "Unique kebab-case skill name, under 64 characters, using lowercase letters, digits, and hyphens"
        ),
      description: z
        .string()
        .trim()
        .min(1)
        .max(SKILL_LIMITS.description)
        .describe(
          "Concise third-person description of what the skill does and the concrete requests or contexts that should trigger it"
        ),
      instructions: z
        .string()
        .trim()
        .min(1)
        .max(SKILL_LIMITS.body)
        .refine(
          (value) => !/^---(?:\r?\n|$)/.test(value.trimStart()),
          "Provide only the Markdown body; YAML frontmatter is generated by the app."
        )
        .describe(
          "Complete concise Markdown body for SKILL.md, written as direct operating instructions. Do not include YAML frontmatter, installation notes, a README, or process commentary"
        ),
    }),
  },
};
