/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppSettingsIndexRouteImport } from './routes/_app.settings.index'
import { Route as AppSettingsSkillsRouteImport } from './routes/_app.settings.skills'
import { Route as AppSettingsModelsRouteImport } from './routes/_app.settings.models'
import { Route as AppSettingsMissionsRouteImport } from './routes/_app.settings.missions'
import { Route as AppSettingsMemoriesRouteImport } from './routes/_app.settings.memories'
import { Route as AppSettingsExpertsRouteImport } from './routes/_app.settings.experts'
import { Route as AppSettingsAppearanceRouteImport } from './routes/_app.settings.appearance'
import { Route as AppSettingsAboutRouteImport } from './routes/_app.settings.about'
import { Route as AppChatChatIdRouteImport } from './routes/_app.chat.$chatId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsSkillsRoute = AppSettingsSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsModelsRoute = AppSettingsModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsMissionsRoute = AppSettingsMissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsMemoriesRoute = AppSettingsMemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsExpertsRoute = AppSettingsExpertsRouteImport.update({
  id: '/experts',
  path: '/experts',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAppearanceRoute = AppSettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAboutRoute = AppSettingsAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppChatChatIdRoute = AppChatChatIdRouteImport.update({
  id: '/chat/$chatId',
  path: '/chat/$chatId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/chat/$chatId': typeof AppChatChatIdRoute
  '/settings/about': typeof AppSettingsAboutRoute
  '/settings/appearance': typeof AppSettingsAppearanceRoute
  '/settings/experts': typeof AppSettingsExpertsRoute
  '/settings/memories': typeof AppSettingsMemoriesRoute
  '/settings/missions': typeof AppSettingsMissionsRoute
  '/settings/models': typeof AppSettingsModelsRoute
  '/settings/skills': typeof AppSettingsSkillsRoute
  '/settings/': typeof AppSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/chat/$chatId': typeof AppChatChatIdRoute
  '/settings/about': typeof AppSettingsAboutRoute
  '/settings/appearance': typeof AppSettingsAppearanceRoute
  '/settings/experts': typeof AppSettingsExpertsRoute
  '/settings/memories': typeof AppSettingsMemoriesRoute
  '/settings/missions': typeof AppSettingsMissionsRoute
  '/settings/models': typeof AppSettingsModelsRoute
  '/settings/skills': typeof AppSettingsSkillsRoute
  '/settings': typeof AppSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/chat/$chatId': typeof AppChatChatIdRoute
  '/_app/settings/about': typeof AppSettingsAboutRoute
  '/_app/settings/appearance': typeof AppSettingsAppearanceRoute
  '/_app/settings/experts': typeof AppSettingsExpertsRoute
  '/_app/settings/memories': typeof AppSettingsMemoriesRoute
  '/_app/settings/missions': typeof AppSettingsMissionsRoute
  '/_app/settings/models': typeof AppSettingsModelsRoute
  '/_app/settings/skills': typeof AppSettingsSkillsRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/chat/$chatId'
    | '/settings/about'
    | '/settings/appearance'
    | '/settings/experts'
    | '/settings/memories'
    | '/settings/missions'
    | '/settings/models'
    | '/settings/skills'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat/$chatId'
    | '/settings/about'
    | '/settings/appearance'
    | '/settings/experts'
    | '/settings/memories'
    | '/settings/missions'
    | '/settings/models'
    | '/settings/skills'
    | '/settings'
  id:
    | '__root__'
    | '/_app'
    | '/_app/settings'
    | '/_app/'
    | '/_app/chat/$chatId'
    | '/_app/settings/about'
    | '/_app/settings/appearance'
    | '/_app/settings/experts'
    | '/_app/settings/memories'
    | '/_app/settings/missions'
    | '/_app/settings/models'
    | '/_app/settings/skills'
    | '/_app/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/skills': {
      id: '/_app/settings/skills'
      path: '/skills'
      fullPath: '/settings/skills'
      preLoaderRoute: typeof AppSettingsSkillsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/models': {
      id: '/_app/settings/models'
      path: '/models'
      fullPath: '/settings/models'
      preLoaderRoute: typeof AppSettingsModelsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/missions': {
      id: '/_app/settings/missions'
      path: '/missions'
      fullPath: '/settings/missions'
      preLoaderRoute: typeof AppSettingsMissionsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/memories': {
      id: '/_app/settings/memories'
      path: '/memories'
      fullPath: '/settings/memories'
      preLoaderRoute: typeof AppSettingsMemoriesRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/experts': {
      id: '/_app/settings/experts'
      path: '/experts'
      fullPath: '/settings/experts'
      preLoaderRoute: typeof AppSettingsExpertsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/appearance': {
      id: '/_app/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AppSettingsAppearanceRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/about': {
      id: '/_app/settings/about'
      path: '/about'
      fullPath: '/settings/about'
      preLoaderRoute: typeof AppSettingsAboutRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/chat/$chatId': {
      id: '/_app/chat/$chatId'
      path: '/chat/$chatId'
      fullPath: '/chat/$chatId'
      preLoaderRoute: typeof AppChatChatIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppSettingsRouteChildren {
  AppSettingsAboutRoute: typeof AppSettingsAboutRoute
  AppSettingsAppearanceRoute: typeof AppSettingsAppearanceRoute
  AppSettingsExpertsRoute: typeof AppSettingsExpertsRoute
  AppSettingsMemoriesRoute: typeof AppSettingsMemoriesRoute
  AppSettingsMissionsRoute: typeof AppSettingsMissionsRoute
  AppSettingsModelsRoute: typeof AppSettingsModelsRoute
  AppSettingsSkillsRoute: typeof AppSettingsSkillsRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsAboutRoute: AppSettingsAboutRoute,
  AppSettingsAppearanceRoute: AppSettingsAppearanceRoute,
  AppSettingsExpertsRoute: AppSettingsExpertsRoute,
  AppSettingsMemoriesRoute: AppSettingsMemoriesRoute,
  AppSettingsMissionsRoute: AppSettingsMissionsRoute,
  AppSettingsModelsRoute: AppSettingsModelsRoute,
  AppSettingsSkillsRoute: AppSettingsSkillsRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppChatChatIdRoute: typeof AppChatChatIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppChatChatIdRoute: AppChatChatIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
