/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppTranscribeRouteImport } from './routes/_app.transcribe'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppSettingsIndexRouteImport } from './routes/_app.settings.index'
import { Route as AppWorkspaceWorkspaceIdRouteImport } from './routes/_app.workspace.$workspaceId'
import { Route as AppSettingsSpeechRouteImport } from './routes/_app.settings.speech'
import { Route as AppSettingsSkillsRouteImport } from './routes/_app.settings.skills'
import { Route as AppSettingsResearchAgentsRouteImport } from './routes/_app.settings.research-agents'
import { Route as AppSettingsNotificationsRouteImport } from './routes/_app.settings.notifications'
import { Route as AppSettingsModelsRouteImport } from './routes/_app.settings.models'
import { Route as AppSettingsMemoriesRouteImport } from './routes/_app.settings.memories'
import { Route as AppSettingsHelpRouteImport } from './routes/_app.settings.help'
import { Route as AppSettingsExpertsRouteImport } from './routes/_app.settings.experts'
import { Route as AppSettingsChangelogRouteImport } from './routes/_app.settings.changelog'
import { Route as AppSettingsAppearanceRouteImport } from './routes/_app.settings.appearance'
import { Route as AppSettingsAboutRouteImport } from './routes/_app.settings.about'
import { Route as AppChatChatIdRouteImport } from './routes/_app.chat.$chatId'
import { Route as AppWorkspaceWorkspaceIdIndexRouteImport } from './routes/_app.workspace.$workspaceId.index'
import { Route as AppWorkspaceWorkspaceIdChatChatIdRouteImport } from './routes/_app.workspace.$workspaceId.chat.$chatId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTranscribeRoute = AppTranscribeRouteImport.update({
  id: '/transcribe',
  path: '/transcribe',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppWorkspaceWorkspaceIdRoute = AppWorkspaceWorkspaceIdRouteImport.update({
  id: '/workspace/$workspaceId',
  path: '/workspace/$workspaceId',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsSpeechRoute = AppSettingsSpeechRouteImport.update({
  id: '/speech',
  path: '/speech',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsSkillsRoute = AppSettingsSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsResearchAgentsRoute =
  AppSettingsResearchAgentsRouteImport.update({
    id: '/research-agents',
    path: '/research-agents',
    getParentRoute: () => AppSettingsRoute,
  } as any)
const AppSettingsNotificationsRoute =
  AppSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AppSettingsRoute,
  } as any)
const AppSettingsModelsRoute = AppSettingsModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsMemoriesRoute = AppSettingsMemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsHelpRoute = AppSettingsHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsExpertsRoute = AppSettingsExpertsRouteImport.update({
  id: '/experts',
  path: '/experts',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsChangelogRoute = AppSettingsChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAppearanceRoute = AppSettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAboutRoute = AppSettingsAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppChatChatIdRoute = AppChatChatIdRouteImport.update({
  id: '/chat/$chatId',
  path: '/chat/$chatId',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkspaceWorkspaceIdIndexRoute =
  AppWorkspaceWorkspaceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppWorkspaceWorkspaceIdRoute,
  } as any)
const AppWorkspaceWorkspaceIdChatChatIdRoute =
  AppWorkspaceWorkspaceIdChatChatIdRouteImport.update({
    id: '/chat/$chatId',
    path: '/chat/$chatId',
    getParentRoute: () => AppWorkspaceWorkspaceIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/transcribe': typeof AppTranscribeRoute
  '/chat/$chatId': typeof AppChatChatIdRoute
  '/settings/about': typeof AppSettingsAboutRoute
  '/settings/appearance': typeof AppSettingsAppearanceRoute
  '/settings/changelog': typeof AppSettingsChangelogRoute
  '/settings/experts': typeof AppSettingsExpertsRoute
  '/settings/help': typeof AppSettingsHelpRoute
  '/settings/memories': typeof AppSettingsMemoriesRoute
  '/settings/models': typeof AppSettingsModelsRoute
  '/settings/notifications': typeof AppSettingsNotificationsRoute
  '/settings/research-agents': typeof AppSettingsResearchAgentsRoute
  '/settings/skills': typeof AppSettingsSkillsRoute
  '/settings/speech': typeof AppSettingsSpeechRoute
  '/workspace/$workspaceId': typeof AppWorkspaceWorkspaceIdRouteWithChildren
  '/settings/': typeof AppSettingsIndexRoute
  '/workspace/$workspaceId/': typeof AppWorkspaceWorkspaceIdIndexRoute
  '/workspace/$workspaceId/chat/$chatId': typeof AppWorkspaceWorkspaceIdChatChatIdRoute
}
export interface FileRoutesByTo {
  '/transcribe': typeof AppTranscribeRoute
  '/': typeof AppIndexRoute
  '/chat/$chatId': typeof AppChatChatIdRoute
  '/settings/about': typeof AppSettingsAboutRoute
  '/settings/appearance': typeof AppSettingsAppearanceRoute
  '/settings/changelog': typeof AppSettingsChangelogRoute
  '/settings/experts': typeof AppSettingsExpertsRoute
  '/settings/help': typeof AppSettingsHelpRoute
  '/settings/memories': typeof AppSettingsMemoriesRoute
  '/settings/models': typeof AppSettingsModelsRoute
  '/settings/notifications': typeof AppSettingsNotificationsRoute
  '/settings/research-agents': typeof AppSettingsResearchAgentsRoute
  '/settings/skills': typeof AppSettingsSkillsRoute
  '/settings/speech': typeof AppSettingsSpeechRoute
  '/settings': typeof AppSettingsIndexRoute
  '/workspace/$workspaceId': typeof AppWorkspaceWorkspaceIdIndexRoute
  '/workspace/$workspaceId/chat/$chatId': typeof AppWorkspaceWorkspaceIdChatChatIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/transcribe': typeof AppTranscribeRoute
  '/_app/': typeof AppIndexRoute
  '/_app/chat/$chatId': typeof AppChatChatIdRoute
  '/_app/settings/about': typeof AppSettingsAboutRoute
  '/_app/settings/appearance': typeof AppSettingsAppearanceRoute
  '/_app/settings/changelog': typeof AppSettingsChangelogRoute
  '/_app/settings/experts': typeof AppSettingsExpertsRoute
  '/_app/settings/help': typeof AppSettingsHelpRoute
  '/_app/settings/memories': typeof AppSettingsMemoriesRoute
  '/_app/settings/models': typeof AppSettingsModelsRoute
  '/_app/settings/notifications': typeof AppSettingsNotificationsRoute
  '/_app/settings/research-agents': typeof AppSettingsResearchAgentsRoute
  '/_app/settings/skills': typeof AppSettingsSkillsRoute
  '/_app/settings/speech': typeof AppSettingsSpeechRoute
  '/_app/workspace/$workspaceId': typeof AppWorkspaceWorkspaceIdRouteWithChildren
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/workspace/$workspaceId/': typeof AppWorkspaceWorkspaceIdIndexRoute
  '/_app/workspace/$workspaceId/chat/$chatId': typeof AppWorkspaceWorkspaceIdChatChatIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/transcribe'
    | '/chat/$chatId'
    | '/settings/about'
    | '/settings/appearance'
    | '/settings/changelog'
    | '/settings/experts'
    | '/settings/help'
    | '/settings/memories'
    | '/settings/models'
    | '/settings/notifications'
    | '/settings/research-agents'
    | '/settings/skills'
    | '/settings/speech'
    | '/workspace/$workspaceId'
    | '/settings/'
    | '/workspace/$workspaceId/'
    | '/workspace/$workspaceId/chat/$chatId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/transcribe'
    | '/'
    | '/chat/$chatId'
    | '/settings/about'
    | '/settings/appearance'
    | '/settings/changelog'
    | '/settings/experts'
    | '/settings/help'
    | '/settings/memories'
    | '/settings/models'
    | '/settings/notifications'
    | '/settings/research-agents'
    | '/settings/skills'
    | '/settings/speech'
    | '/settings'
    | '/workspace/$workspaceId'
    | '/workspace/$workspaceId/chat/$chatId'
  id:
    | '__root__'
    | '/_app'
    | '/_app/settings'
    | '/_app/transcribe'
    | '/_app/'
    | '/_app/chat/$chatId'
    | '/_app/settings/about'
    | '/_app/settings/appearance'
    | '/_app/settings/changelog'
    | '/_app/settings/experts'
    | '/_app/settings/help'
    | '/_app/settings/memories'
    | '/_app/settings/models'
    | '/_app/settings/notifications'
    | '/_app/settings/research-agents'
    | '/_app/settings/skills'
    | '/_app/settings/speech'
    | '/_app/workspace/$workspaceId'
    | '/_app/settings/'
    | '/_app/workspace/$workspaceId/'
    | '/_app/workspace/$workspaceId/chat/$chatId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transcribe': {
      id: '/_app/transcribe'
      path: '/transcribe'
      fullPath: '/transcribe'
      preLoaderRoute: typeof AppTranscribeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/workspace/$workspaceId': {
      id: '/_app/workspace/$workspaceId'
      path: '/workspace/$workspaceId'
      fullPath: '/workspace/$workspaceId'
      preLoaderRoute: typeof AppWorkspaceWorkspaceIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/speech': {
      id: '/_app/settings/speech'
      path: '/speech'
      fullPath: '/settings/speech'
      preLoaderRoute: typeof AppSettingsSpeechRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/skills': {
      id: '/_app/settings/skills'
      path: '/skills'
      fullPath: '/settings/skills'
      preLoaderRoute: typeof AppSettingsSkillsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/research-agents': {
      id: '/_app/settings/research-agents'
      path: '/research-agents'
      fullPath: '/settings/research-agents'
      preLoaderRoute: typeof AppSettingsResearchAgentsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/notifications': {
      id: '/_app/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AppSettingsNotificationsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/models': {
      id: '/_app/settings/models'
      path: '/models'
      fullPath: '/settings/models'
      preLoaderRoute: typeof AppSettingsModelsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/memories': {
      id: '/_app/settings/memories'
      path: '/memories'
      fullPath: '/settings/memories'
      preLoaderRoute: typeof AppSettingsMemoriesRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/help': {
      id: '/_app/settings/help'
      path: '/help'
      fullPath: '/settings/help'
      preLoaderRoute: typeof AppSettingsHelpRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/experts': {
      id: '/_app/settings/experts'
      path: '/experts'
      fullPath: '/settings/experts'
      preLoaderRoute: typeof AppSettingsExpertsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/changelog': {
      id: '/_app/settings/changelog'
      path: '/changelog'
      fullPath: '/settings/changelog'
      preLoaderRoute: typeof AppSettingsChangelogRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/appearance': {
      id: '/_app/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AppSettingsAppearanceRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/about': {
      id: '/_app/settings/about'
      path: '/about'
      fullPath: '/settings/about'
      preLoaderRoute: typeof AppSettingsAboutRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/chat/$chatId': {
      id: '/_app/chat/$chatId'
      path: '/chat/$chatId'
      fullPath: '/chat/$chatId'
      preLoaderRoute: typeof AppChatChatIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workspace/$workspaceId/': {
      id: '/_app/workspace/$workspaceId/'
      path: '/'
      fullPath: '/workspace/$workspaceId/'
      preLoaderRoute: typeof AppWorkspaceWorkspaceIdIndexRouteImport
      parentRoute: typeof AppWorkspaceWorkspaceIdRoute
    }
    '/_app/workspace/$workspaceId/chat/$chatId': {
      id: '/_app/workspace/$workspaceId/chat/$chatId'
      path: '/chat/$chatId'
      fullPath: '/workspace/$workspaceId/chat/$chatId'
      preLoaderRoute: typeof AppWorkspaceWorkspaceIdChatChatIdRouteImport
      parentRoute: typeof AppWorkspaceWorkspaceIdRoute
    }
  }
}

interface AppSettingsRouteChildren {
  AppSettingsAboutRoute: typeof AppSettingsAboutRoute
  AppSettingsAppearanceRoute: typeof AppSettingsAppearanceRoute
  AppSettingsChangelogRoute: typeof AppSettingsChangelogRoute
  AppSettingsExpertsRoute: typeof AppSettingsExpertsRoute
  AppSettingsHelpRoute: typeof AppSettingsHelpRoute
  AppSettingsMemoriesRoute: typeof AppSettingsMemoriesRoute
  AppSettingsModelsRoute: typeof AppSettingsModelsRoute
  AppSettingsNotificationsRoute: typeof AppSettingsNotificationsRoute
  AppSettingsResearchAgentsRoute: typeof AppSettingsResearchAgentsRoute
  AppSettingsSkillsRoute: typeof AppSettingsSkillsRoute
  AppSettingsSpeechRoute: typeof AppSettingsSpeechRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsAboutRoute: AppSettingsAboutRoute,
  AppSettingsAppearanceRoute: AppSettingsAppearanceRoute,
  AppSettingsChangelogRoute: AppSettingsChangelogRoute,
  AppSettingsExpertsRoute: AppSettingsExpertsRoute,
  AppSettingsHelpRoute: AppSettingsHelpRoute,
  AppSettingsMemoriesRoute: AppSettingsMemoriesRoute,
  AppSettingsModelsRoute: AppSettingsModelsRoute,
  AppSettingsNotificationsRoute: AppSettingsNotificationsRoute,
  AppSettingsResearchAgentsRoute: AppSettingsResearchAgentsRoute,
  AppSettingsSkillsRoute: AppSettingsSkillsRoute,
  AppSettingsSpeechRoute: AppSettingsSpeechRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppWorkspaceWorkspaceIdRouteChildren {
  AppWorkspaceWorkspaceIdIndexRoute: typeof AppWorkspaceWorkspaceIdIndexRoute
  AppWorkspaceWorkspaceIdChatChatIdRoute: typeof AppWorkspaceWorkspaceIdChatChatIdRoute
}

const AppWorkspaceWorkspaceIdRouteChildren: AppWorkspaceWorkspaceIdRouteChildren =
  {
    AppWorkspaceWorkspaceIdIndexRoute: AppWorkspaceWorkspaceIdIndexRoute,
    AppWorkspaceWorkspaceIdChatChatIdRoute:
      AppWorkspaceWorkspaceIdChatChatIdRoute,
  }

const AppWorkspaceWorkspaceIdRouteWithChildren =
  AppWorkspaceWorkspaceIdRoute._addFileChildren(
    AppWorkspaceWorkspaceIdRouteChildren,
  )

interface AppRouteChildren {
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppTranscribeRoute: typeof AppTranscribeRoute
  AppIndexRoute: typeof AppIndexRoute
  AppChatChatIdRoute: typeof AppChatChatIdRoute
  AppWorkspaceWorkspaceIdRoute: typeof AppWorkspaceWorkspaceIdRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppTranscribeRoute: AppTranscribeRoute,
  AppIndexRoute: AppIndexRoute,
  AppChatChatIdRoute: AppChatChatIdRoute,
  AppWorkspaceWorkspaceIdRoute: AppWorkspaceWorkspaceIdRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
